services:

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  app:
    image: eclipse-temurin:21
    container_name: blogging-platform-app
    environment:
      ENVIRONMENT: test
      DB_URL: jdbc:mysql://mysql:3306/blog_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    working_dir: /app
    command: ["./gradlew", "clean", "bootRun"]
    ports:
      - "9090:9090"
    depends_on:
      - mysql

volumes:
  my-db-data:
