services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
volumes:
  my-db-data:
