spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  output:
    ansi:
      enabled: always

server:
  servlet:
    context-path: /v1/blogging-platform

# Logging configuration
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
    '[org.deimos.projects.bloggingplatformapi]': DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true

  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
  use-management-port: false
  enable-javadoc: true
  show-actuator: true
  packages-to-scan: org.deimos.projects.bloggingplatformapi.controller